# 应用名称
spring:
  application:
    name: DigitalRiskPrevention
  # THYMELEAF (ThymeleafAutoConfiguration)
  # 开启模板缓存（默认值： true ）
  thymeleaf:
    cache: false
    check-template: true # 检查模板是否存在，然后再呈现
    check-template-location: true # 检查模板位置是否正确（默认值 :true ）
    content-type: text/html #Content-Type 的值（默认值： text/html ）
    enabled: true # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8
    prefix: classpath:/templates/ # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.131.104.165:3307/requirement_data?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: cmcc2023test

  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 10MB
# 应用服务 WEB 访问端口
server:
  port: 8099
  servlet:
    context-path: /DigitalRiskPrevention

mybatis-plus:
  type-aliases-package: com.example.digitalriskprevention.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework.web: DEBUG
    com.fileman: DEBUG
    root: WARN
  file:
    path: @system.filePath@/log
